---
title: 'Lab #4'
author: "Braedon Giblin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggplot2)

defense <- read_excel('cyclonesFootball2020.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2020.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2020.xlsx', sheet='Biography')

defense19 <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense19 <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography19 <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
```

## Part 1: Cleaning Data

1.  The player names and opponent names as factors

    Answer:
    ```{R}
    defClean <- defense %>%
      mutate(across(Name:Opponent_Opponent, as.factor))
    
    offClean <- offense %>%
      mutate(across(Name:Opponent_Opponent, as.factor))
    
    bioClean <- biography %>%
      mutate(across(Name:Position, as.factor)) %>%
      mutate(across(Class:Highschool, as.factor))
    

    ```

2.  All offensive and defensive statistics are numerical.

    Answer:
    ```{R}
    defClean <- defClean %>%
      #mutate(across(Tackles_Solo:Pass_PB, ~replace_na(.x, 0))) %>%
      mutate(across(Tackles_Solo:Pass_PB, as.numeric))
    
    offClean <- offClean %>%
      #mutate(across(Receiving_REC:Passing_INT, ~replace_na(.x, 0))) %>%
      mutate(across(Receiving_REC:Passing_INT, as.numeric))
      
    bioClean <- bioClean %>%
      mutate(Weight=as.numeric(Weight))
    
    ```
    
3.  Height as numeric

    Answer:
    ```{R}
    bioClean <- bioClean %>%
      separate(Height, c('height.feet', 'height.inches')) %>%
      mutate(Height=((as.numeric(height.feet) * 12) + as.numeric(height.inches))) %>%
      select(-height.feet) %>% select(-height.inches)
    
    str(defClean)
    str(offClean)
    str(bioClean)
    ```

## Part 2: Tidying Data

1.  Reformat the `offClean` data frame into a tidy format using `pivot_longer`. The type of statistic is added as a new key column named stat

    Answer:
    ```{R}
    pivOffClean <- offClean %>%
      pivot_longer(Receiving_REC:Passing_INT, names_to='stat', values_to='value') %>%
      drop_na()
    
    ```

2.  Show the distributions of each stat

    Answer:
    ```{R}
    pivOffClean %>%
      ggplot(aes(x=value)) + geom_histogram() + facet_wrap(~stat, scales='free')
    ```


3.  Did ISU have better offense against Oregon or Oklahoma

    Answer:
    ```{R}
    offClean %>%
      filter(Opponent_Opponent %in% c('Oklahoma', 'Oregon')) %>%
      pivot_wider(names_from='Opponent_Opponent', values_from='Receiving_YDS', values_fn = mean) %>%
      ggplot(aes(x=Oklahoma, y=Oregon)) + geom_point()
    ```
    
    The above plot seems to suggest we do better against Oklahoma, as on average each receiver got more yards against oklahoma than they did against Oregon



4.  Separate the hometown column int two cols.


    Answer:
    ```{R}
    bioClean <- bioClean %>%
      separate(Hometown, c('City', 'State'), sep=', ')
    
    bioClean %>%
      head(5)
    ```

5. How many players from each state

    Answer:
    ```{R}
    bioClean %>%
      ggplot(aes(x=State)) + geom_bar() + theme(axis.text.x = element_text(angle = 45))
    
    bioClean %>%
      count(State)
    ```

## Part 3: Joining Dataframes

1.  find which states do the ISU players come from.

    Answer:
    ```{R}
    defSub <- defClean %>%
      mutate(Side='defense') %>%
      select(Name, Side) %>%
      left_join(bioClean, by='Name')
    
    offSub <- offClean %>%
      mutate(Side='offense') %>%
      select(Name, Side) %>%
      left_join(bioClean, by='Name')
      
    
    defSub %>%
      ggplot(aes(x=State)) + geom_bar() + theme(axis.text.x = element_text(angle = 45))
    
    defSub %>%
      count(State)
    
    offSub %>%
      ggplot(aes(x=State)) + geom_bar() + theme(axis.text.x = element_text(angle = 45))
    
    offSub %>%
      count(State)
      
    ```
    
    The above shows all of the defenders and offenders that are from each state, both graphically and in a tabular format.

2.  How does the performance of quarterback Brock Purdy relate to the performance of the ISU team?

    Answer:
    ```{R}
    offClean %>%
      select(-Passing_TD) %>%
      left_join(
        offClean %>%
          filter(Name == 'Purdy, Brock') %>%
          select(Opponent_Opponent, Passing_TD),
        by='Opponent_Opponent'
      ) %>%
      mutate(Passing_TD=as.factor(Passing_TD)) %>%
      ggplot(aes(x=Passing_TD, y=Receiving_YDS)) + geom_boxplot()
    ```
    
    The number of receiving Yards seems to slightly increase on average as the amount of touchdowns thrown by Purdy increase. This would make sense because to throw more touchdowns, the receivers would also need to make more touchdown receptions for more yards.
    
    
3.  Who improved the most?

    Answer:
    ```{R}
    s <- offense19 %>%
      mutate(across(Name:Opponent_Opponent, as.factor)) %>%
      mutate(across(Receiving_REC:Passing_INT, as.numeric)) %>%
      select(Name, Receiving_YDS, Opponent_Opponent) %>%
      group_by(Name) %>%
      summarise(mean_yds_2019 = mean(Receiving_YDS, na.rm = TRUE))
      
    s2 <- offClean %>%
      group_by(Name) %>%
      summarise(mean_yds_2020 = mean(Receiving_YDS, na.rm = TRUE))
    
    s %>%
      inner_join(s2, by='Name') %>%
      mutate(delta=as.numeric(mean_yds_2020 - mean_yds_2019, na.rm=TRUE)) %>%
      drop_na() %>%
      filter(delta == max(delta))
      

      
    ```
    
    Landen Akers is the most improved player. This is shown by comparing all players average reception yardage in 2019 with 2020. Akers had the greatest improvement of an average of 14 yards per game improvement. 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    



